# Generated by Django 4.2.7 on 2023-12-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinadores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinador',
            old_name='número_documento',
            new_name='numero_documento',
        ),
    ]
