# Generated by Django 4.2.7 on 2023-12-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_coordinadores', '0002_alter_coordinador_options'),
        ('app_coordinadores', '0002_rename_número_documento_coordinador_numero_documento'),
    ]

    operations = [
    ]
