# Generated by Django 4.2.7 on 2023-11-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido', 'nombre']},
        ),
    ]
