# Generated by Django 4.2.7 on 2023-12-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleados', '0002_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id']},
        ),
    ]
