# Generated by Django 4.2.7 on 2023-12-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['apellido', 'nombre']},
        ),
    ]
