# Generated by Django 4.2.7 on 2023-11-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0003_delete_coordinador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
