# Generated by Django 4.2.7 on 2023-12-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0006_reservaservicio_cliente_reservaservicio_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_reservada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
