# Generated by Django 4.2.7 on 2023-12-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0006_reservaservicio_cliente_reservaservicio_empleado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservaservicio',
            old_name='responsable',
            new_name='coordinador',
        ),
    ]
