# Generated by Django 4.2.7 on 2023-12-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0007_alter_reservaservicio_fecha_reservada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_reservada',
            field=models.DateField(),
        ),
    ]
