# Generated by Django 4.2.7 on 2023-12-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservas', '0007_rename_responsable_reservaservicio_coordinador'),
        ('app_reservas', '0008_alter_reservaservicio_fecha_reservada'),
    ]

    operations = [
    ]
